203 java impl
OA-PASS/pass-download-service pull request #12
Opened 2022-11-14 07:16 UTC by maggieolaya

I restructured my files so that they match up with the java implementation branch. I also fixed some java syntax errors in my naming and in my code. This week I began looking into the web service aspect of the service and am figuring out which classes I want to have interacting with it. I also am in the midst of finding equivalent java imports to the ones in the GO files and figuring out which classes need which.

2022-11-14 13:49 UTC, markpatton requested changes
Make sure all the class names are in camel case starting with an uppercase letter.
Make sure all method names are in camel case starting with a lowercase letter.

Add .DS_Store to .gitignore and remove those files from git.

Add a github action to build and test the service. Base it on an existing one like pass-doi-service .github/workflows/ci.yml. (Just copy the file to the right place and edit it slightly.)

Make sure "mvn verify" completes successfully. The GitHub action will run it for you when you push commits.

2022-11-14 13:49 UTC, markpatton commented on pom.xml
>    <dependencies>
Some of the variables used for versions are not defined.

2022-11-14 13:49 UTC, markpatton commented on src/main/java/org/eclipse/pass/download/Main.java
> +package org.eclipse.pass.manuscript;
Is there a need for a command line application? What does it do?

2022-11-14 13:49 UTC, markpatton commented on src/main/java/org/eclipse/pass/download/Serve.java
> +package org.eclipse.pass.manuscript;
Name the class something like DownloadServlet. Also make the "/lookup" to match the existing service and your documentation.

2022-11-28 13:46 UTC, maggieolaya commented
Created class to hold information about the manuscripts, obtained from DOI lookup. Working on building and writing JSON files. Added more to servlet outline.

2022-12-12 01:23 UTC, maggieolaya commented
I believe I am finished with designing my service and ready to move to implementation. I am having trouble with the checkstyle errors, they don't show up on my end but only show up when I create the pull request.

2022-12-14 15:57 UTC, markpatton commented
@maggieolaya 

The checkstyle errors should show up if you run
```
mvn verify
```

2022-12-14 15:59 UTC, markpatton commented on src/main/java/org/eclipse/pass/manuscript/Unpaywall.java
> +  public Manuscript[] lookup(String doi) {
May want to return a List<Manuscript> instead, but an array is fine too.

2022-12-14 16:00 UTC, markpatton requested changes
Look good! Just need to get the checkstyle errors fixed and I'll merge.

2022-12-17 01:15 UTC, markpatton approved these changes

2022-12-17 01:15 UTC, merged